version: '3.9'
services:
  app:
    user: node
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
      - ~/.ssh:/home/node/.ssh
      - ~/.gitconfig:/home/node/.gitconfig
    command: /bin/sh -c "while sleep 1000; do :; done"
